POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "content": "aasd",
  "number": "1"
}

###

PUT http://localhost:3001/api/persons/62bc3ec2861b8a8ca1e8bfaa
Content-Type: application/json

{
  "content":"Arto Hellas",
  "number": "1"
}

###

DELETE http://localhost:3001/api/persons/62bc377cbe312ff6e99f19fb

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "content": "asdasda22",
  "number": "1"
}

###